### ISSUE TITLE
Notifications != Activity

### ISSUE THREAD

**Issue by codemasher** [barredo/mastodeck#57]
Hi! I wonder why the "Notifications" tab is called "Activity" when it actually shows... the notifications?

"Activity" is an entirely different thing - at least in legacy TweetDeck, where it shows the likes etc. of the people I'm following - I'd love to see that here too (because i live and thrive from the activity timeline) - I just wonder if that's technically possible without server side aggregation.

While I'm at notifications: the "follow <account>" link at the bottom of each notification - even from people I'm following - feels bloaty and superfluous. A button like in the Mastodon web client would be more appropriate.

```css
/* sorry... */
.column[type="notifications"] .actions.mt-2{
    display:none;
}
```
