### ISSUE TITLE
Link hover styles?

### ISSUE THREAD

**Issue by codemasher** [barredo/mastodeck#58]
Right now MastoDeck feels pretty "dead" because there are no hover styles - not even simple underlines? The `pointer` cursor is basically everywhere and i have no clue what happens if I click.
Please make it look more "alive". Customizable link colors would be cool too! 🙂 

Quick fix via injected CSS:
```css
a:hover, a:active, a:focus{
    text-decoration: underline;
}
```
